version: "3.7"

services:
    postgres:
        image: postgres
        restart: always
        container_name: postgres1
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - classman_dev_data:/var/lib/postgresql/data
        ports:
            - 5432:5432

volumes:
    classman_dev_data: {}
